name: Build pex & deb

on: push

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"
      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
      - run: nix-channel --update
      - run: ./pex.sh
      - run: ./deb.sh
      - name: Store pex
        uses: actions/upload-artifact@v4
        with:
          name: pex
          path: robot_failover.pex
      - name: Store deb
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: robot_failover.deb
